### ISSUE TITLE
session.install("foo") doesn't honor [[tool.poetry.source]]

### ISSUE THREAD

**Issue by kentmartin73** [cjolowicz/nox-poetry#497] opened 2021-10-20 16:32 UTC
Hi,

We're using internal PyPi repos, and, when using `session.install("foo")`, the repos defined in `[[tool.poetry.source]]` are ignored.

Short of reading `pyproject.toml` and constructing/writing a `pip.conf` before doing any `session.install`s, is there another obvious way forward?  If not, would this fit better into nox-poetry itself?

**Comment by cjolowicz** [comment] 2021-11-15 11:04
Duplicate of #398

**Closed by cjolowicz** 2021-11-15 11:04 UTC
Labels: enhancement
