### ISSUE TITLE
No dev dependecies are installed

### ISSUE THREAD

**Issue by devtud** [cjolowicz/nox-poetry#230] opened 2021-01-09 10:30 UTC
When I run `nox` my tests cannot be run because the dev dependencies listed in `pyproject.toml` are not installed. I expect the line
```python
#noxfile.py
...
    session.install(".")
...
```
installs all dependencies (including dev ones).

In order to have dev dependencies installed, I have to explicitly install them in session, eg:
```python
#noxfile.py
...
    session.install(".")
    session.install("aiounittest")
...
```

Installing the dev dependencies manually is not a good idea because I need to keep the `pyproject.toml` as the single source of truth.

However, in the requirements file created per each environment the dev dependencies **are** listed, eg:
```
#.nox/tests-3-6/tmp/requirements.txt
...
aiounittest==1.4.0; python_version >= "3.6" and python_version < "3.8"
...
```

but it seems they are not installed.

Below I highlight my setup:

Packages installed at system level:
- poetry
- nox
- nox-poetry

```toml
#pyproject.toml

[tool.poetry.dependencies]
python = "^3.6"
httpx = "^=0.16.1"
typing-extensions = {version = "^3.7.4", python = "~3.6 || ~3.7"}

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^5.1"}
docker = "^=4.4.1"
black = "^=20.8b1"
aiounittest = {version = "^1.4.0", python = "~3.6 || ~3.7"}
```

```python
#noxfile.py

import nox
import nox_poetry.patch  # noqa
from nox.sessions import Session


@nox.session(python=["3.6", "3.7", "3.8", "3.9"])
def tests(session: Session) -> None:
    session.run("pip", "--version")
    session.run("pip", "install", "pip==20.2.4")
    session.run("poetry", "lock")
    session.install(".")
    session.run("python", "-m", "unittest")
```

Run `nox`:

```bash
$ nox
nox > Running session tests-3.6
nox > Creating virtual environment (virtualenv) using python3.6 in .nox/tests-3-6
nox > pip --version
pip 20.3.1 from [...]/.nox/tests-3-6/lib/python3.6/site-packages/pip (python 3.6)
nox > pip install pip==20.2.4
Collecting pip==20.2.4
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.1
    Uninstalling pip-20.3.1:
      Successfully uninstalled pip-20.3.1
Successfully installed pip-20.2.4
nox > poetry lock
nox > Warning: poetry is not installed into the virtualenv, it is located at /[...]/.local/bin/poetry. This might cause issues! Pass external=True into run() to silence this message.
Updating dependencies
Resolving dependencies... (8.3s)
nox > poetry build --format=wheel
nox > pip uninstall --yes file:///[...]/dist/my_project-0.1.0-py3-none-any.whl#sha256=7b37d980135517485e27d2763a766a9b95bba1d54d2d2cdcb38bafc66d03fe92
nox > poetry export --format=requirements.txt --output=.nox/tests-3-6/tmp/requirements.txt --dev --without-hashes
nox > python -m pip install --constraint=.nox/tests-3-6/tmp/requirements.txt file:///[...]/dist/my_project-0.1.0-py3-none-any.whl#sha256=7b37d980135517485e27d2763a766a9b95bba1d54d2d2cdcb38bafc66d03fe92
nox > python -m unittest
[...]
ModuleNotFoundError: No module named 'aiounittest'
```

```
#.nox/tests-3-6/tmp/requirements.txt

aiounittest==1.4.0; python_version >= "3.6" and python_version < "3.8"
appdirs==1.4.4; python_version >= "3.6"
black==20.8b1; python_version >= "3.6"
certifi==2020.12.5; python_version >= "3.6"
click==7.1.2; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6"
contextvars==2.4; python_version < "3.7" and python_version >= "3.6"
coverage==5.3.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0" and python_version < "4")
dataclasses==0.8; python_version >= "3.6" and python_version < "3.7"
docker==4.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0")
h11==0.12.0; python_version >= "3.6"
httpcore==0.12.2; python_version >= "3.6"
httpx==0.16.1; python_version >= "3.6"
idna==3.1; python_version >= "3.6"
immutables==0.14; python_version < "3.7" and python_version >= "3.6"
mypy-extensions==0.4.3; python_version >= "3.6"
pathspec==0.8.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6"
pywin32==227; python_version >= "2.7" and python_full_version < "3.0.0" and sys_platform == "win32" or python_full_version >= "3.5.0" and sys_platform == "win32"
regex==2020.11.13; python_version >= "3.6"
requests==2.15.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
rfc3986==1.4.0; python_version >= "3.6"
six==1.15.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
sniffio==1.2.0; python_version >= "3.6"
toml==0.10.2; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4" and python_version >= "3.6"
typed-ast==1.4.2; python_version >= "3.6"
typing-extensions==3.7.4.3; python_version >= "3.6" and python_version < "3.8" or python_version >= "3.6"
websocket-client==0.57.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
wrapt==1.12.1; python_version >= "3.6" and python_version < "3.8"
```

**Comment by cjolowicz** [comment] 2021-01-14 14:47
Hi @devtud thank you for this feedback!

As you noticed, the current behavior of `session.install(".")` is to install only dependencies that appear in the metadata of the distribution package built by Poetry for your project, which excludes development dependencies. This is by design. It allows you to have isolated environments for your automated tasks. For example, you don't need to install documentation generators into an environment that is used for type checking. This is also what would happen in your Nox session if you did not have nox-poetry installed. The main reason for having `nox-poetry` is not to use Poetry as an installer rather than pip. It is to make Nox and pip honor Poetry's lock file, while keeping everything else as much the same as possible.

That said, if you prefer to use Poetry as an installer and install all development dependencies into each session, you can simply use `session.run("poetry", "install", external=True)` in your noxfile. In that case, you won't need nox-poetry at all.

The README has some more information about this in the section titled "Why?".

I'm going to close this for now, but feel free to reach out if you have any further questions.

**Closed by cjolowicz** 2021-01-14 14:47 UTC

**Comment by KyleKing** [comment] 2021-06-06 17:07
I have a use case where I think I need to install `dev-dependencies`

1. I have a main package [`calcipy` that defines extras](https://github.com/KyleKing/calcipy/blob/main/pyproject.toml#L174) and uses [those extras in nox-poetry](https://github.com/KyleKing/calcipy/blob/main/calcipy/dev/noxfile.py#L115)
2. Each package built on `calcipy` has both a dependency and a dev-dependency (where the latter specifies extras from calcipy)
3. This way, `calcipy` can bootstrap a project with minimal core functionality and development-only testing and static analysis

As an example, my project `recipes` has a poetry section like this ([full file](https://github.com/KyleKing/recipes/blob/main/pyproject.toml))

```toml
[tool.poetry.dependencies]
python = "^3.9"
calcipy = "^0.3"

[tool.poetry.dev-dependencies]
calcipy = { version = "^0.3", extras = ["dev", "lint", "test", "commitizen_legacy"] }
```

*The problem is that I want to use nox-poetry to test different Python versions, but I can't define `calcipy` as a both a development dependency and an optional extra* (or at least that doesn't possible), so I don't have a way to install the `calcipy` extras with `nox-poetry`, unless I go around and use external poetry instead (which I've done as a temporary workaround)

**Comment by cjolowicz** [comment] 2021-06-06 19:01
What happens if￼ you do this?

```python 
session.install(".", "calcipy[dev,lint]")
```

**Comment by KyleKing** [comment] 2021-06-06 20:33
Awesome, that seems to work!

https://github.com/KyleKing/calcipy/commit/28915463ab89d7be5cd8c7324740f4b0fd0163af
