### ISSUE TITLE
Possibly clear the pip cache?

### ISSUE THREAD

**Issue by gitonthescene** [cjolowicz/nox-poetry#404] opened 2021-06-22 00:58 UTC
Hello,

I just got bit when trying to change my [`pyproject.toml`](https://github.com/gitonthescene/csv-reconcile/blob/master/pyproject.toml) file to start using an [external lib](https://github.com/python/importlib_metadata) for higher Python versions than I had been.  That is to say, I had the following in my `pyproject.toml`:

``` python
importlib_metadata = { version = ">=3.7.3,<5.0.0", python = "~3.7" }
```

and I wanted to change it to the following:

``` python
importlib_metadata = { version = ">=3.7.3,<5.0.0", python = "<3.10" }
```

But `nox` wasn't picking up this change.  Actually, `pip` wasn't picking it up either because it was using the [`pip cache`](https://pip.pypa.io/en/stable/cli/pip_cache/).  This took me a while to figure out, unfortunately.

This makes me wonder if the pip cache should be cleared during `nox` runs.  For a strictly "independent environment" I would think so, but I appreciate that this can be a big hit on performance.  Maybe just clear the cache for the packages in the current `poetry` project?  Maybe make it optional?  Maybe at least show what's cached?

This fixed my problem:

``` sh
$ . ./.nox/test-3-8/bin/activate
(test-3-8) $  python -m pip cache list
Cache contents:

 - black-20.8b1-py3-none-any.whl (124 kB)
 - csv_reconcile-0.1.2-cp37-cp37m-macosx_11_0_x86_64.whl (46 kB)
 - csv_reconcile-0.2.1-cp37-cp37m-macosx_11_0_x86_64.whl (46 kB)
 - csv_reconcile-0.2.3-cp37-cp37m-macosx_11_0_x86_64.whl (47 kB)
 - csv_reconcile-0.2.5-cp37-cp37m-macosx_11_0_x86_64.whl (47 kB)
 - csv_reconcile-0.2.5-cp38-cp38-macosx_11_0_x86_64.whl (56 kB)
 - csv_reconcile-0.2.5-cp39-cp39-macosx_11_0_x86_64.whl (56 kB)
 - csv_reconcile_geo-0.1.0-py3-none-any.whl (2.1 kB)
 - httpretty-1.1.2-py3-none-any.whl (28 kB)
 - importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
 - ordered_set-4.0.2-py2.py3-none-any.whl (8.2 kB)
 - poetry_core-1.0.2-py2.py3-none-any.whl (424 kB)
 - pyrsistent-0.16.1-cp38-cp38-macosx_11_0_x86_64.whl (67 kB)
 - pytest_sugar-0.9.4-py2.py3-none-any.whl (9.0 kB)
 - setuptools-54.2.0-py3-none-any.whl (785 kB)
 - setuptools_scm-6.0.1-py3-none-any.whl (27 kB)
 - termcolor-1.1.0-py3-none-any.whl (4.8 kB)
(test-3-8) $  python -m pip cache remove csv_reconcile
Files removed: 6
(test-3-8) $  
```

Again, my particular problem is fixed.  I just thought this might be something worth considering.  If this happens to me again, my bet is it will take me just as long to diagnose.

Regards

**Comment by cjolowicz** [comment] 2021-11-15 05:52
Duplicate of #377

**Closed** 2021-11-15 05:52 UTC

**Comment by cjolowicz** [comment] 2021-11-15 10:57
Fixed in #523

**Comment by gitonthescene** [comment] 2021-11-15 22:04
Thank you!
